# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160530_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='height',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
