# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20160530_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='height',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='width',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
