# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20160530_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='height',
            field=models.IntegerField(blank=True, help_text='optional', null=True),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(help_text='max. 5 megabytes', upload_to=b'', verbose_name='Select a file'),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='width',
            field=models.IntegerField(default=255, help_text='required', null=True),
        ),
    ]
