# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20160604_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
